# Generated by Django 3.0.3 on 2020-03-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='post_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
