# Generated by Django 3.0.3 on 2020-07-20 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200720_1335'),
        ('product', '0003_auto_20200716_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('MASSAGE', 'Massage'), ('SALON', 'Salon'), ('AC', 'AC Repair'), ('CLEANING', 'Cleaning'), ('ELECTRICIAN', 'Electrician'), ('PLUMBER', 'Plumber'), ('FITNESS', 'Fitness'), ('MISCELLANEOUS', 'Misc')], default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='accepted',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.FreelancerProfile'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Item'),
        ),
    ]
