# Generated by Django 3.0.3 on 2020-07-16 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.CustomerProfile'),
        ),
        migrations.AddField(
            model_name='address',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='users.FreelancerProfile'),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='PIN'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='State'),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('name', 'customer')},
        ),
    ]
