# Generated by Django 3.0.3 on 2020-07-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200716_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, choices=[('Hyd', 'Hyderabad'), ('MAS', 'Chennai'), ('Bom', 'Mumbai')], max_length=20, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='location',
            field=models.TextField(choices=[('Hyd', 'Hyderabad'), ('MAS', 'Chennai'), ('Bom', 'Mumbai')], default='Hyd'),
        ),
        migrations.AlterField(
            model_name='freelancerprofile',
            name='location',
            field=models.TextField(choices=[('Hyd', 'Hyderabad'), ('MAS', 'Chennai'), ('Bom', 'Mumbai')], default='Hyd'),
        ),
    ]
