# Generated by Django 3.0.3 on 2020-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_freelancer',
            field=models.BooleanField(default=False),
        ),
    ]
