# Generated by Django 3.0.3 on 2020-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200310_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerprofile',
            name='location',
            field=models.TextField(choices=[('Hyd', 'Hyderabad'), ('MAS', 'Chennai')], default='Hyd'),
        ),
    ]
