# Generated by Django 3.0.3 on 2020-03-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200324_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(blank=True, default='icon.png', upload_to='profile_image'),
        ),
    ]
